# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeteer', '0002_auto_20161226_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
            preserve_default=False,
        ),
    ]
