# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeteer', '0003_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
    ]
