# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeteer', '0004_auto_20161231_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='description',
        ),
        migrations.AddField(
            model_name='objective',
            name='completed',
            field=models.CharField(choices=[('IP', 'In Progress'), ('Y', 'Yes'), ('N', 'No')], default='IP', max_length=2),
        ),
        migrations.AddField(
            model_name='objective',
            name='name',
            field=models.CharField(default='Objective', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='objective',
            field=models.CharField(choices=[('Spend', "Don't spend more than"), ('Have', 'Have more than')], default='Spend', max_length=5),
        ),
    ]
