# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeteer', '0005_auto_20170113_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='description',
            field=models.CharField(default='Description', max_length=512),
            preserve_default=False,
        ),
    ]
